import { Column, Entity, ManyToOne, PrimaryGeneratedColumn } from "typeorm";
import { Vsix } from "./vsix";

/**
 * The VSIX Verison
 *
 * @export
 * @class VsixVersion
 */
@Entity()
export class VsixVersion {
    /**
     * Primary key autogenerated id of the version
     *
     * @type {string}
     * @memberof VsixVersion
     */
    @PrimaryGeneratedColumn('uuid')
    id!: string;

    /**
     * THe parent vsix
     *
     * @type {Vsix}
     * @memberof VsixVersion
     */
    @ManyToOne(() => Vsix, vsix => vsix.versions)
    vsix?: Vsix;

    /**
     * The Version string of the vsix
     *
     * @type {string}
     * @memberof VsixVersion
     */
    @Column()
    version!: string;

    /**
     * The description of the version
     *
     * @type {string}
     * @memberof VsixVersion
     */
    @Column({ default: '' })
    description!: string;

    /**
     * The filename assembled out of the publisher, the id and this version
     *
     * @readonly
     * @memberof VsixVersion
     */
    get filename() {
        return `${this.vsix?.publisher}.${this.vsix?.id}-${this.version}.vsix`;
    }
}